// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
namespace Creep
{
	public enum ETargetType
	{
		None = 0,
		Infantry = 1,
		Mechanical = 2,
		FlyingMechanical = 4,
		AnyMechanical = 6,
	}
}

