// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using Apex.Units;
using Apex.Steering.Components;


namespace ApexUtils
{
	public class ExtendedUnitFacade : UnitFacade
	{
		private HumanoidSpeedComponent _speeder;

		public ExtendedUnitFacade ()
		{
		}

		public override void Initialize (UnityEngine.GameObject unitObject)
		{
			base.Initialize (unitObject);

			_speeder = unitObject.GetComponent<HumanoidSpeedComponent>();
		}

		public void Run() {
			_speeder.Run();

		}
	}
}

