// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;


namespace CreepSpawnerPackage
{
	[System.Serializable]
	public class Wave
	{
		public WaveUnits[] units;
		private WaveUnits processingUnits;
		public int thisUnitIndex = -1;
		public float countToThisWave = 20;
		public bool complete = false;
		public Wave ()
		{
		}

		public void Update() {
			
		}
		public void processWave() {
			if(countToThisWave>0f) {
				countToThisWave -= Time.deltaTime;
			} else {
				if(processingUnits==null||processingUnits.creepCount==0) {
					thisUnitIndex++;
					if(thisUnitIndex<units.Length) {
						processingUnits = units[thisUnitIndex];
					} else { 
						complete = true;
					}
				} else { 
					// Start releasing these unit
					processingUnits.processUnits();
				}
			}
		}
	}
}

