// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using FlightPathManager;
using UnityEngine;


namespace FlightPathManager
{
	public class BanzaiFlightPath : FlightPathFollower
	{

		public GameObject target;
		
		public float cruiseAltitude = 8f;
		public BanzaiFlightPath ()
		{

		}

		void Update() {
			if(target!=null&&currentNode.transform.position.magnitude==0) {
			//	this.currentNode = new Vector3(target.transform.position.x,target.transform.position.y,cruiseAltitude);
			}
		}
	}
}

