// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;


namespace FlightPathManager
{
	public class FlightPathPoint : MonoBehaviour
	{
		public int dropBombsHere = 0;
		public bool chooseBanzaiTargetHere = false;
		public bool hasEscapedHere = false;
		public FlightPathPoint ()
		{
		}
	}
}

