// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
 
	public enum ETowerTypes
	{
		BasicTower = 0,
		FireTower = 1,
		LaserTower =2,
		CannonTower = 3,
		ElectroTower = 4,
		MoneyTower = 5,
	}

