// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;


namespace TowerScripts
{
	public class NozzleRecoilBase : MonoBehaviour
	{
		public NozzleRecoilBase ()
		{
		}

		public void recoil() {
			iTween.MoveBy(this.gameObject, iTween.Hash("z", -0.08, "easeType",iTween.EaseType.spring, "loopType", "none", "delay", .0,"time",0.1));
			iTween.MoveBy(this.gameObject, iTween.Hash("z", 0.08, "easeType",iTween.EaseType.spring, "loopType", "none", "delay", .2,"time",0.1));
		

}
	}
}

