// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;

public class InterfaceManagerUtils : MonoBehaviour
{
	public InterfaceManagerUtils ()
	{
	}

 
	public static void confirmTowerWindow(WWTD_Tower aTower) {
		cleanAllInterfaceWindows();
		GameObject g = Instantiate(Resources.Load("UI/TowerPlacement/ConfirmBuyTower")) as GameObject;
		ConfirmBuyTower ct = g.GetComponent<ConfirmBuyTower>();
		ct.initTower(aTower);
	}
	public static void showUpgradeTower(WWTD_Tower aTower) {
		cleanAllInterfaceWindows();
		GameObject g = Instantiate(Resources.Load("UI/TowerPlacement/DoUpgradeTower")) as GameObject;
		TowerUpgradeOptions ct = g.GetComponent<TowerUpgradeOptions>();
		ct.initTower(aTower);
	}
	public static void cleanAllInterfaceWindows() {
		GameObject[] g = GameObject.FindGameObjectsWithTag("UIWindow");
		for(int i = 0;i<g.Length;i++) {
			Destroy(g[i]);
		}
	}
}
